services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: test_db
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
